awk -v Cname="   C5" -v Hname="  H51" -f gro_OP.awk runPROT.gro
awk -v Cname="   C5" -v Hname="  H52" -f gro_OP.awk runPROT.gro
awk -v Cname="   C6" -v Hname="  H61" -f gro_OP.awk runPROT.gro
awk -v Cname="   C6" -v Hname="  H62" -f gro_OP.awk runPROT.gro
awk -v Cname="  C12" -v Hname=" H121" -f gro_OP.awk runPROT.gro
awk -v Cname="  C12" -v Hname=" H122" -f gro_OP.awk runPROT.gro
awk -v Cname="  C13" -v Hname=" H131" -f gro_OP.awk runPROT.gro
awk -v Cname="  C30" -v Hname=" H301" -f gro_OP.awk runPROT.gro
awk -v Cname="  C30" -v Hname=" H302" -f gro_OP.awk runPROT.gro
