awk -v Cname="  C21" -v Hname="  H41" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C21" -v Hname="  H42" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C22" -v Hname="  H51" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C22" -v Hname="  H52" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C23" -v Hname="  H61" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C23" -v Hname="  H62" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname="  C11" -v Hname="   H7" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname=" C218" -v Hname="  H81" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
awk -v Cname=" C218" -v Hname="  H82" -f /home/ollilas1/Dropbox/codes/gro_OP.awk runPROT.gro
